dir.create("raw_data")
dir.create("clean_data")
dir.create("scripts")
dir.create("results")
dir.create("plots")
data <- read.csv(file.choose())
View(data)
str(data)
data$gender_fac <- as.factor(data$gender)
str(data)
data$gender_num <- ifelse(data$gender_fac == "Female",1,0)
class(data$gender_num)
data$gender_num <- as.factor(data$gender_num)
class(data$gender_num)
data$diagnosis_fec <- as.factor(data$diagnosis)
str(data)
data$diagnosis_fec <- factor(data$diagnosis_fec,levels = c("Normal","Cancer"))
levels(data$diagnosis_fec)
data$smoker_fac <- as.factor(data$smoker)
str(data)
data$smoker_num <- ifelse(data$smoker_fac == "No",0,1)
write.csv(data, file = "patient_info_clean.csv", row.names = FALSE)
